spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_mgmt
    username: postgres
    password: "Sachin@123"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none      # we will manage schema manually with your SQL file
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: false        # disable Flyway for now while things stabilise

server:
  port: 9090

jwt:
  secret: THIS_IS_A_DEV_SECRET_PLEASE_CHANGE_32_CHARS_LONG_123456
  expiration-ms: 86400000
